{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled .Values.mongodb.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  labels:
    app: mercury
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default (randAlphaNum 16) | b64enc | quote }}
  mongodb-passwords: {{ .Values.mongodb.auth.rootPassword | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}